// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/burapha44/example/api/v1/controllers"
	"github.com/burapha44/example/api/v1/middleware"
	"github.com/burapha44/example/api/v1/services"
)

// Injectors from wire.go:

func NewAppContainer() (*AppContainer, error) {
	baseMiddleware := middleware.NewBaseMiddleware()
	baseService := services.NewBaseService()
	baseController := controllers.NewBaseController(baseService)
	appContainer := &AppContainer{
		AuthMiddleware: baseMiddleware,
		BaseController: baseController,
	}
	return appContainer, nil
}

// wire.go:

type AppContainer struct {
	AuthMiddleware *middleware.BaseMiddleware
	BaseController *controllers.BaseController
}
