definitions:
  services.DependencyStatus:
    properties:
      message:
        type: string
      response_time_ms:
        type: integer
      status:
        type: string
    type: object
  services.ServerInfoResponse:
    properties:
      dependencies:
        additionalProperties:
          $ref: '#/definitions/services.DependencyStatus'
        type: object
      environment:
        type: string
      hostname:
        type: string
      message:
        type: string
      service_name:
        type: string
      status:
        type: string
      timestamp:
        type: string
      uptime:
        description: Or int for seconds
        type: string
      version:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/ProductController/info:
    get:
      description: Get server info and dependencies status and uptime of server and
        more
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.ServerInfoResponse'
      summary: Get Server Info
      tags:
      - ProductController
  /api/v1/server/info:
    get:
      description: Get server info and dependencies status and uptime of server and
        more
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.ServerInfoResponse'
      summary: Get Server Info
      tags:
      - Base
swagger: "2.0"
